[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python llm_main.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10