name = "bs-blogreader-frontend"
compatibility_date = "2024-01-15"

[build]
command = "cd frontend && npm run build"
output = "frontend/dist"

[env.production.vars]
# 生产环境变量将在Cloudflare Pages设置中配置
# VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
# VITE_SUPABASE_ANON_KEY = "your_anon_key_here"