name = "bs-blogreader-frontend"
compatibility_date = "2024-01-15"

# Cloudflare Pages configuration
pages_build_output_dir = "frontend/dist"

# 生产环境变量将在Cloudflare Pages设置中配置
[env.production.vars]
# VITE_SUPABASE_URL = "https://oqicgfaczdmrdoglkqzi.supabase.co"
# VITE_SUPABASE_ANON_KEY = "your_anon_key_here"